# 제주도 시,읍,면 별 위도 경도 데이터 프레임 생성
- 최종 dts 인덱스

In [1]:
import pandas as pd
import numpy as np
import json
from tqdm import tqdm

jeju_geo = json.load(open('./hangjeongdong_제주특별자치도.geojson', encoding='utf8'))

In [2]:
key=['경도_Lng','위도_Lat','행정구역']
lng_lst=[]
lat_lst=[]
region_lst=[]

for geo in jeju_geo['features']:
    
    if geo['properties']['adm_nm'].find('동')==-1:
        region=geo['properties']['adm_nm']
    else:
        if geo['properties']['adm_nm'].find('제주시')==-1:
            region='제주특별자치도 서귀포시'
        else:
            region='제주특별자치도 제주시'
    
    for i in range(len(geo['geometry']['coordinates'])):
        for lng,lat in geo['geometry']['coordinates'][i][0]:
            region_lst.append(region)
            lng_lst.append(lng)
            lat_lst.append(lat)

In [3]:
jeju_df=pd.DataFrame(dict(zip(key,[lng_lst,lat_lst,region_lst])))
jeju_df

          경도_Lng     위도_Lat             행정구역
0     126.231279  33.404747  제주특별자치도 제주시 한림읍
1     126.229939  33.404130  제주특별자치도 제주시 한림읍
2     126.225890  33.404090  제주특별자치도 제주시 한림읍
3     126.225005  33.404220  제주특별자치도 제주시 한림읍
4     126.224876  33.404246  제주특별자치도 제주시 한림읍
...          ...        ...              ...
9846  126.445924  33.358612     제주특별자치도 서귀포시
9847  126.446883  33.358621     제주특별자치도 서귀포시
9848  126.447337  33.358617     제주특별자치도 서귀포시
9849  126.448301  33.358551     제주특별자치도 서귀포시
9850  126.448734  33.358517     제주특별자치도 서귀포시

[9851 rows x 3 columns]

In [4]:
jeju_df.describe(include='all')

             경도_Lng       위도_Lat          행정구역
count   9851.000000  9851.000000          9851
unique          NaN          NaN            14
top             NaN          NaN  제주특별자치도 서귀포시
freq            NaN          NaN          2386
mean     126.524719    33.404457           NaN
std        0.176404     0.154842           NaN
min      126.143699    33.111868           NaN
25%      126.420745    33.296930           NaN
50%      126.523424    33.378267           NaN
75%      126.611638    33.480709           NaN
max      126.972982    34.013401           NaN

In [5]:
jeju_df['경도_Lng']=jeju_df['경도_Lng'].map(lambda x:x-x%.001)
jeju_df['위도_Lat']=jeju_df['위도_Lat'].map(lambda x:x-x%.001)

jeju_df.head()

    경도_Lng  위도_Lat             행정구역
0  126.231  33.404  제주특별자치도 제주시 한림읍
1  126.229  33.404  제주특별자치도 제주시 한림읍
2  126.225  33.404  제주특별자치도 제주시 한림읍
3  126.225  33.404  제주특별자치도 제주시 한림읍
4  126.224  33.404  제주특별자치도 제주시 한림읍

In [6]:
jeju_df.describe(include='all')

             경도_Lng       위도_Lat          행정구역
count   9851.000000  9851.000000          9851
unique          NaN          NaN            14
top             NaN          NaN  제주특별자치도 서귀포시
freq            NaN          NaN          2386
mean     126.524215    33.403963           NaN
std        0.176403     0.154846           NaN
min      126.143000    33.111000           NaN
25%      126.420000    33.296000           NaN
50%      126.523000    33.378000           NaN
75%      126.611000    33.480000           NaN
max      126.972000    34.013000           NaN

In [7]:
jeju_df=jeju_df.drop_duplicates()
jeju_df.describe(include='all')

             경도_Lng       위도_Lat          행정구역
count   5503.000000  5503.000000          5503
unique          NaN          NaN            14
top             NaN          NaN  제주특별자치도 서귀포시
freq            NaN          NaN          1025
mean     126.528976    33.406901           NaN
std        0.199625     0.160167           NaN
min      126.143000    33.111000           NaN
25%      126.368000    33.304000           NaN
50%      126.525000    33.378000           NaN
75%      126.658000    33.474000           NaN
max      126.972000    34.013000           NaN

In [8]:
regions=jeju_df['행정구역'].unique()
regions

array(['제주특별자치도 제주시 한림읍', '제주특별자치도 제주시 애월읍', '제주특별자치도 제주시 구좌읍',
       '제주특별자치도 제주시 조천읍', '제주특별자치도 제주시 한경면', '제주특별자치도 제주시 추자면',
       '제주특별자치도 제주시 우도면', '제주특별자치도 제주시', '제주특별자치도 서귀포시 대정읍',
       '제주특별자치도 서귀포시 남원읍', '제주특별자치도 서귀포시 성산읍', '제주특별자치도 서귀포시 안덕면',
       '제주특별자치도 서귀포시 표선면', '제주특별자치도 서귀포시'], dtype=object)

In [9]:
# 서귀포시 = region
min1=jeju_df[np.logical_and(jeju_df['행정구역']=='제주특별자치도 서귀포시', jeju_df['위도_Lat']==np.sort(jeju_df[jeju_df['행정구역']=='제주특별자치도 서귀포시']['위도_Lat'].unique())[0])]['경도_Lng'].min()
max1=jeju_df[np.logical_and(jeju_df['행정구역']=='제주특별자치도 서귀포시', jeju_df['위도_Lat']==np.sort(jeju_df[jeju_df['행정구역']=='제주특별자치도 서귀포시']['위도_Lat'].unique())[0])]['경도_Lng'].max()
for num in np.arange(min1,max1,.001):
    num='{:.3f}'.format(num)
    print(num,type(num))

126.515 <class 'str'>
126.516 <class 'str'>
126.517 <class 'str'>
126.518 <class 'str'>

In [10]:
key=['경도_Lng-위도_Lat','행정구역']
lng_lat_lst=[]
region_lst=[]

for region in tqdm(regions):
    lats=np.sort(jeju_df[jeju_df['행정구역']==region]['위도_Lat'].unique())
    for lat in lats:
        min_lng=jeju_df[np.logical_and(jeju_df['행정구역']==region, jeju_df['위도_Lat']==lat)]['경도_Lng'].min()
        max_lng=jeju_df[np.logical_and(jeju_df['행정구역']==region, jeju_df['위도_Lat']==lat)]['경도_Lng'].max()
        lngs=np.arange(min_lng,max_lng+.001,.001)
        for lng in lngs:
            lng='{:.3f}'.format(lng)
            lng_lat_lst.append(lng+'_'+str(lat))
            region_lst.append(region)

100%|██████████| 14/14 [00:11<00:00,  1.23it/s]

In [11]:
df_final=pd.DataFrame(dict(zip(key,[lng_lat_lst,region_lst])))
df_final.head(10)

    경도_Lng-위도_Lat             행정구역
0  126.298_33.319  제주특별자치도 제주시 한림읍
1  126.299_33.319  제주특별자치도 제주시 한림읍
2  126.300_33.319  제주특별자치도 제주시 한림읍
3   126.294_33.32  제주특별자치도 제주시 한림읍
4   126.295_33.32  제주특별자치도 제주시 한림읍
5   126.296_33.32  제주특별자치도 제주시 한림읍
6   126.297_33.32  제주특별자치도 제주시 한림읍
7   126.298_33.32  제주특별자치도 제주시 한림읍
8  126.293_33.321  제주특별자치도 제주시 한림읍
9  126.294_33.321  제주특별자치도 제주시 한림읍

In [12]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101098 entries, 0 to 101097
Data columns (total 2 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   경도_Lng-위도_Lat  101098 non-null  object
 1   행정구역           101098 non-null  object
dtypes: object(2)
memory usage: 1.5+ MB

In [13]:
df_final.describe()

         경도_Lng-위도_Lat          행정구역
count           101098        101098
unique           97225            14
top     126.806_33.443  제주특별자치도 서귀포시
freq                 3         22813

In [14]:
df_final.duplicated().sum()

0